spring:
  application:
    name: chungchun-university
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chungchundb
    username: ohgiraffers
    password: ohgiraffers
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
#  sql:
#    init:
#      data-locations: classpath*:chungchundb/post.sql
#      mode: always
#      platform: mysql
logging:
  level:
    root: info